### ISSUE TITLE
DOC: remove double curly braces in the DataFrame.add_prefix docstring

### ISSUE THREAD

**Issue by jorisvandenbossche** [noatamir/scipy-2023-sprint#10]
In the online docs (https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.add_prefix.html), we see there are double curly braces for the `axis` keyword specification:

![image](https://github.com/noatamir/scipy-2023-sprint/assets/1020496/6f43eade-1032-4714-a10f-e06e508ae5b5)

This should be single curly braces (to indicate the unique values that the keyword can take)

**Comment by vvaidy** [comment]
take

**Comment by vvaidy** [comment]
Fixed and opened a PR which is now pending review

**Comment by rhshadrach** [comment]
https://github.com/pandas-dev/pandas/pull/54142 has been merged; closing.
